{ 
	'name': 'ITB Planning Edit', 
	'description': 'Planning Edit, the ITB way',
	'category': 'Plan Edit',
	'author': 'Housny M.', 
	'depends': ['base'],
	'data': [
		'views/price.xml',
		'views/confirmation.xml',
		'views/evaluation.xml',
		'views/implementation.xml',
		'views/indicator.xml',
		'views/initiative.xml',
		'views/menu.xml',
		'views/plan.xml',
		'views/program.xml',
		'views/relocation.xml',
		'views/request.xml',
		'views/spending_actual.xml',
		'views/spending.xml',
		'views/target.xml',
		'views/unit.xml',
		'wizard/budget_manager_wizard.xml',
		'views/ado.xml',
		'views/pagu.xml',
		'views/allocation.xml',
		'views/plan_int.xml',
		'views/initiative_int.xml',
		'views/spending_int.xml',
		'views/tax.xml',
		'views/tax_line.xml',
		'views/bank_statement.xml',
		'views/request_dko.xml',
		'views/dko_int.xml',
		'views/dko_lines.xml',
		'views/reimburse.xml',
		'views/custom_view.xml',
		'views/cash_advance.xml',
		'views/request_line.xml',
		'views/request_alocation.xml',
	],
	'qweb': ['static/src/xml/qweb.xml'],
	'version': '0.1',
	'application':True,
	'installable': True,
	'auto_install': False, 
} 