# Docker Compose file for development

version: '2.1'
services:

  odoo:
    image: odoo:10
    command: /bin/bash -c "sleep 5 && odoo --db_host postgres --db_port 5432 --db_user odoo --db_password odoo -d banpt --test-enable -i banpt_report_generator -u banpt_report_generator"
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./src:/mnt/extra-addons

  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_db_data:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"
    environment:
      - DEFAULT_USER=odoo
      - DEFAULT_PASSWORD=odoo
    depends_on:
      - postgres

volumes:
  odoo_web_data:
    driver: local
  odoo_db_data:
    driver: local
