{ 
    'name': 'ITB Academic', 
    'description': 'Academic Management, the ITB way',
    'category': 'Academic',
    'author': 'Housny M.', 
    'depends': ['base','hr'],
    'data': [
        'views/structure.xml',
        'views/menu.xml',
        'views/attendance.xml',
        'views/catalog.xml',
        'views/counselor.xml',
        'views/course.xml',
        'views/curriculum.xml',
        'views/defence.xml',
        'views/grade.xml',
        'views/graduation.xml',
        'views/offering.xml',
        'views/outcome.xml',
        'views/participant.xml',
        'views/performance.xml',
        'views/program.xml',
        'views/res_partner.xml',
        'views/rubric.xml',
        'views/semester.xml',
        'views/thesis.xml',
        'views/employee.xml',
    ], 
    'version': '0.1',
	'application':True,
	'installable': True,
	'auto_install': False, 
} 