import attendance
import catalog
import counselor
import course
import curriculum
import defence
import employee
import evaluation
import grade
import graduation
import instructor
import lecture
import meetup
import offering
import outcome
import partner
import participant
import performance
import program
import rubric
import semester
import structure
import thesis
import topic