# -*- coding: utf-8 -*-

REGULAR_STUDENT = 0
TRANSFER_STUDENT = 1
NONREGULAR_STUDENT = 2

TRANSFER_STUDENT_NIM_START = 600
TRANSFER_STUDENT_NIM_END = 699
NONREGULAR_STUDENT_NIM_START = 800
NONREGULAR_STUDENT_NIM_END = 899
