{ 
    'name': 'QMS', 
    'description': 'Quality Management System, the Indonesian way',
    'category': 'Manufacturing',
    'author': 'Odoonesia (info@odoonesia.com)', 
    'depends': ['base','product'],
    'website':'http://odoonesia.com/qa',
    'data': [
        'views/menu.xml',
        'views/capa.xml',
        'views/vendor.xml',
        'views/product.xml',
        'views/audit.xml',
        'views/claim.xml',
        'views/evaluation.xml',
        'views/makloon.xml',
        'views/inbound.xml',
        'views/assesment.xml',
        'views/production.xml',
        'views/coa.xml',
        'views/committee.xml',
        'views/parameter.xml',
                    ], 
    'version': '0.1',
	'application':True,
	'installable': True,
	'auto_install': False, 
} 