{ 
    'name': 'PII', 
    'description': 'PII Membership Management',
    'category': 'Employees',
    'author': 'Odoonesia (info@odoonesia.com)', 
    'depends': ['base'],
    'data': [
        'views/menu.xml',
        'views/membership.xml',
        'views/award.xml',
        'views/creation.xml',
        'views/education.xml',
        'views/language.xml',
        'views/proceeding.xml',
        'views/profile.xml',
        'views/publication.xml',
        'views/research.xml',
        'views/seminar.xml',
        'views/teaching.xml',
        'views/training.xml',
        'views/work.xml',
    ], 
    'version': '0.1',
	'application':True,
	'installable': True,
	'auto_install': False, 
} 